version: '2'
services:
    car_spotters_front-elasticsearch:
        container_name: car_spotters_front-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/car_spotters_front/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
